### ISSUE TITLE
Feature: pass pre-parse function to markdown task

### ISSUE THREAD

**Issue by edannenberg** [hashobject/perun#105]
Use case:

Our editors want to set, for example, the `rel`  or `target` attribute for links while using markdown syntax. Inspired by Jekyll I extended the markdown syntax for our frontend editor like so:

```
[foo](bar.html){:rel "nofollow" :blank? true :title "foo bar"}
```

The tag is handled (replaced with final html) via re-seq/read-string before the frontend markdown parser does it's magic for the preview. Now I would like to be able to pass a `:pre-parse-fn` to the perun markdown task to do the same for the backend part.

Took a stab at the feature but as the markdown parsing happens in it's own pod this seems impossible?
Ideally the passed function would run after https://github.com/hashobject/perun/blob/master/src/io/perun/markdown.clj#L97

I could probably create a separate task that does the pre processing before the markdown task but would like to hear your opinions first. Happy to create a PR if this is somehow feasible.

**Comment by Deraen** [comment]
You can pass symbol to pods and then resolve the symbol to function in the pod, similar to: https://github.com/hashobject/perun/blob/master/src/io/perun.clj#L387-L388

In this case you pretty much need to def the function in some namespace instead of writing it inline in build.boot. Also to reflect changes to the function you would need to use tools.namespace or such to reload changed namespaces.

**Comment by edannenberg** [comment]
Thanks @Deraen, I've put up a quick draft PR. Does the job for my needs, hopefully I didn't break anything else in the process. :p
