### ISSUE TITLE
Link to Getting Started

### ISSUE THREAD

**Issue by Robsteranium** [hashobject/perun#91]
I would like to suggest that the readme and perun.io site ought to link to the [Getting Started guide](https://github.com/hashobject/perun/wiki/Getting-Started).

In fact perhaps the site itself would benefit from some concise instructions?

**Comment by Robsteranium** [comment]
Ah sorry - I've now seen the installation/ usage instructions on the readme - I'd not seen this before as I just expected them to come before plugins/ examples so didn't actually read far enough. Oops.

Still I wonder if the perun.io site ought to include a bare bones example. Maybe something like the following...

Create a `/build.boot`: with the configuration and a build task:

``` clojure
(set-env!
 :source-paths #{"src" "source"}
 :dependencies '[[org.clojure/clojure "1.7.0"]
                 [perun "0.3.0"]])

(require '[io.perun :refer :all]
         '[example.core])

(deftask build []
  (comp (markdown)
        (render :renderer 'example.core/renderer)
        (target)))
```

Make some content, e.g. `source/index.md`:

```
# My blog
Is short
```

Write a renderer, e.g.`src/example/core.clj`:

``` clojure
(ns example.core)

(defn renderer [data]
  (str
   "<html><body>"
   (-> data :entry :content)
   "</body></html>"))
```

Then run the build task:

```
$ boot build
```

And your static site gets rendered, e.g. `target/publi/index.html`:

```
<html>
  <body>
    <h1><a href="#my-blog" name="my-blog"></a>My blog</h1>
    <p>Is short</p>
  </body>
</html>
```

**Comment by podviaznikov** [comment]
@Robsteranium thanks for the feedback. You are completely right that site needs to include such example. I didn't do much time with the site yet, I hope to do it in the next month, right now it's just a stub.
I ideally I want to have examples folder with few sites (one page site with perun, blog with perun, multi-page site with perun etc) and guides how to do each type as you suggested

**Comment by jmarca** [comment]
Respectfully I'd like to add my vote for this.  Working through the example projects helps, but a complete worked example that touches all the plugins would help more.  And I didn't find the help page linked here until I found this issue!  For example, the line in the `README.md` that says "See documentation for each task.." should point to where that documentation is (I still can't find that, although in the REPL I can do stuff like `(doc p/markdown)` but that output isn't really enough documentation for someone as clueless as I am).

Here's what I _want_ to know how to do, coming at this cold and having just explored Hugo.  (Also, please be aware that I'm new to clojure/clojurescript).  

First, what I want to do is use a templating engine to generate pages (maybe enlive?).  So I want to know how the "render" function is supposed to work, and what needs to be done by the passed in ":renderer" function, and how to hack it to use enlive to render the site scaffolding, then drop in blobs of markdown content for blog entries, code documentation, etc etc.

So I inspected the working examples from that perspective.  The functions passed to  "perun/render" seem to do the rendering directly using hiccup.  The functions also seem to pull out key-value pairs from metadata, and then access the main body of markdown by looking for :content.  Obviously there are conventions going on here, and the main README gives some hints, but I've never used metadata in markdown aside from title blocks in Pandoc.

Again, the working sites help, but I'm doing a lot of trial and error [cargo cult](https://en.wikipedia.org/wiki/Cargo_cult#Metaphorical_uses_of_the_term) programming.  I don't want to give up on this because it seems like it could be great, but I'm spending a lot of time just trying to get a basic site up.  

In contrast, [Hugo templates](http://gohugo.io/templates/overview/) were much easier to grok and set up and the example themes are super easy to modify, yielding more readily to "learn by doing".

**Comment by podviaznikov** [comment]
@jmarca this is a very good feedback. Thanks a lot!
@martinklepsch made initial guide and he also made a site http://doohn2jgwdztw.cloudfront.net/guides/getting-started/. Hopefully that would become `perun.io` soon. We really need to push it. Because really current version of `perun.io` is mostly a old stub I made.

Also it seems that Guides "http://doohn2jgwdztw.cloudfront.net/guides/" would help a lot in a future when ready. Unfortunately for now no one is working on new guides.

Your question with templates triggers whole new discussion I think. Before templates and rendering were orthogonal to perun. I personally need to think more about it.

BTW, if you still struggling with perun feel free to jump on Clojure Slack #perun channel http://clojurians.net/. Someone there would definitely would be able to help and explain some concepts

**Comment by podviaznikov** [comment]
Closing now, since perun.io has proper site with guide

**Comment by jmarca** [comment]
Thanks for the updated perun.io site.
