### ISSUE TITLE
`permalink` depends on `slug`

### ISSUE THREAD

**Issue by pesterhazy** [hashobject/perun#99]
By default, the `permalink` task only works if the `slug` ask was run previously. This caught me off-guard.

Possible solutions:
- call slug if metadata key not already present?
- throw an exception at runtime if slog is not present
- warn at runtime if slug is not present
- add documentation

**Comment by martinklepsch** [comment]
There's the `SPEC.md` file which notes this dependency but we should definitely become smarter about errors in this context.  Slightly elm-inspired here's an idea for an error that could be shown when the slug is missing. 

![screenshot 2016-09-08 17 55 23](https://cloud.githubusercontent.com/assets/97496/18354326/cc6b564e-75ed-11e6-8919-9c62c685a29f.png)

Because slug-fn and similar parts of perun are swappable we can't do something fully generic at the task level I believe but maybe we can use `clojure.spec` or similar on default fn's to give this kind of feedback.

**Comment by podviaznikov** [comment]
I like this type of feedback. Looks super beginner friendly

**Comment by Deraen** [comment]
And we could probably use puget to colorize the output + shorten long fields (string over 80 chars or such), so we don't manually need to dissoc long fields (content).

**Comment by Deraen** [comment]
And this is once again a place we would need to throw a exception to stop Boot pipeline, but showing the stacktrace wouldn't make much sense. But this should be fixed in the next Boot version: https://github.com/boot-clj/boot/issues/486

**Comment by martinklepsch** [comment]
This is what I used to omit long values :D

``` clojure
(defn omit-long-vals [m]
  (reduce-kv (fn [m k v]
               (if (and (string? v) (< 150 (count v)))
                 (assoc m k ::omitted)
                 m))
             m
             m))
```

**Comment by bhagany** [comment]
Fixed as of https://github.com/hashobject/perun/commit/4638cd5baa1a2ff8d7d3c0e8293cb2264d60b3e1.

`:slug`, `:permalink`, and `:canonical-url`\* are now based on a file's path in the fileset, and automatically set for you when metadata is accessed.  In many cases, this means you don't need to run the `slug` and `permalink` tasks at all, but you still can, if you want to move the files to new locations, based on a slug or permalink.  The `canonical-url` task is deprecated, because there is no advantage to moving a file given a new canonical url, over a new permalink.

\* note, you still must have the `:base-url` global metadata set in order for `:canonical-url` to be set for you.
